# Words/Phrases to exclude from the generated captions (Case Insensitive)
BLACKLIST = [
    "Eijiro Kirishima",
    "Izuku Midoriya",
    "Katsuki Bakugo",
    "My Hero Academia",
    "Ochaco Uraraka",
    "Shoto Todoroki",
    "abs",
    "bara",
    "black hair",
    "blonde hair",
    "braided hair",
    "chubby",
    "dark hair",
    "green hair",
    "kurama",
    "large breasts",
    "large pectorals",
    "lean female",
    "long dark blue hair",
    "medium build",
    "medium length hair",
    "muscular",
    "naruto",
    "naruto (series)",
    "naruto uzumaki",
    "orange hair",
    "pecs",
    "physiques",
    "red hair",
    "short black hair",
    "short hair",
    "six-pack abs",
    "spiky hair",
    "wet hair",
    "white hair",
    "yellow hair"
]

